name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |

            # Pull latest frontend image
            docker pull sowmiyakumar/sleeky-frontend:latest

            # Stop & remove old frontend container
            docker stop sleeky-frontend || true
            docker rm sleeky-frontend || true

            # Run frontend container
            docker run -d \
              --name sleeky-frontend \
              -p 3000:80 \
              sowmiyakumar/sleeky-frontend:latest

            # Pull latest backend image
            docker pull sowmiyakumar/sleeky-backend:latest

            # Stop & remove old backend container
            docker stop sleeky-backend || true
            docker rm sleeky-backend || true

            # Run backend container
            docker run -d \
              --name sleeky-backend \
              -p 8080:80 \
              sowmiyakumar/sleeky-backend:latest
